/**
 * Core Registry — Upstream-owned
 *
 * Contains all sample/reference prototypes shipped with Radiant Play.
 * Maintained by the main maintainer only. Designers: do not edit this file.
 * Add your own prototypes to registry-mine.ts instead.
 */

import React from 'react';

// ── Types & interfaces ────────────────────────────────────────────────────────

export interface ProjectMeta {
  /** Unique identifier (folder name) */
  id: string;
  /** Display name */
  name: string;
  /** Project description */
  description?: string;
  /** Project author/designer */
  author?: string;
  /** Last modified date */
  lastModified?: string;
  /** Thumbnail image path */
  thumbnail?: string;
  /** Project component */
  component: React.ComponentType;
  /** Number of shared Radiant design system components used */
  dsComponents?: number;
  /** Number of custom/local components created for this prototype */
  customComponents?: number;
  /** Which gallery section: 'sample' for built-in examples, 'mine' for user-created (default) */
  section?: 'sample' | 'mine';
}

// ── Thumbnails ────────────────────────────────────────────────────────────────

import AdminGroupsThumbnail from './thumbnails/AdminGroups.svg';
import SpotterMemoryThumbnail from './thumbnails/SpotterMemory.svg';
import SpotterModelThumbnail from './thumbnails/SpotterModel.svg';
import AdminLangThumbnail from './thumbnails/AdminLang.svg';
import MiniSpottersThumbnail from './thumbnails/MiniSpotters.svg';
import LiveboardTemplateThumbnail from './thumbnails/LiveboardTemplate.svg';
import DataModelEditorThumbnail from './thumbnails/DataModelEditor.svg';

// ── Components (lazy-loaded) ──────────────────────────────────────────────────

const SpotterMemory = React.lazy(() => import('./SpotterMemory'));
const AdminGroups = React.lazy(() => import('./AdminGroups'));
const SpotterModelProto = React.lazy(() => import('./SpotterModel'));
const AdminLang = React.lazy(() => import('./AdminLang'));
const MiniSpotters = React.lazy(() => import('./MiniSpotters'));
const LiveboardTemplate = React.lazy(() => import('./_liveboard-template'));
const SalesDashboard = React.lazy(() => import('./SalesDashboard'));
const DataModelEditorSample = React.lazy(() => import('./DataModelEditor'));

// ── Registry ──────────────────────────────────────────────────────────────────

export const coreRegistry: ProjectMeta[] = [
  {
    id: 'SpotterMemory',
    name: 'Spotter Memory',
    description: 'Memory Sources object table experience with search, filtering, and pagination.',
    author: 'Design Team',
    lastModified: '2026-02-19',
    thumbnail: SpotterMemoryThumbnail,
    component: SpotterMemory,
    dsComponents: 6,
    customComponents: 5,
    section: 'sample',
  },
  {
    id: 'AdminGroups',
    name: 'Admin Groups',
    description: 'Group creation wizard with bulk org assignment and role management.',
    author: 'Design Team',
    lastModified: '2026-02-19',
    thumbnail: AdminGroupsThumbnail,
    component: AdminGroups,
    dsComponents: 9,
    customComponents: 10,
    section: 'sample',
  },
  {
    id: 'SpotterModel',
    name: 'Spotter Model',
    description: 'SpotterModel agent edit flow — onboarding, table/join recommendations, columns editing, and impact-aware delete.',
    author: 'Design Team',
    lastModified: '2026-03-03',
    thumbnail: SpotterModelThumbnail,
    component: SpotterModelProto,
    dsComponents: 5,
    customComponents: 14,
    section: 'sample',
  },
  {
    id: 'AdminLang',
    name: 'Admin language settings',
    description: 'Admin settings for CSV-based translation of Liveboards and Answers with upload, validation, and object picker.',
    author: 'Design Team',
    lastModified: '2026-03-12',
    thumbnail: AdminLangThumbnail,
    component: AdminLang,
    dsComponents: 10,
    customComponents: 4,
    section: 'sample',
  },
  {
    id: 'MiniSpotters',
    name: 'MiniSpotters',
    description: 'Curated, domain-specific Spotter instances with bounded context, prompt libraries, and simulated chat.',
    author: 'Design Team',
    lastModified: '2026-03-12',
    thumbnail: MiniSpottersThumbnail,
    component: MiniSpotters,
    dsComponents: 8,
    customComponents: 5,
    section: 'sample',
  },
  {
    id: '_liveboard-template',
    name: 'Liveboard template',
    description: 'Starter template for Liveboard prototypes — includes AnswerTile, KPI tile, bar chart, and SpotterViz panel.',
    author: 'Design Team',
    lastModified: '2026-03-17',
    thumbnail: LiveboardTemplateThumbnail,
    component: LiveboardTemplate,
    dsComponents: 8,
    customComponents: 4,
    section: 'sample',
  },
  {
    id: 'SalesDashboard',
    name: 'Sales Dashboard',
    description: 'Liveboard prototype — view and edit modes with SpotterViz.',
    author: 'Design Team',
    lastModified: '2026-04-03',
    component: SalesDashboard,
    dsComponents: 6,
    customComponents: 3,
    section: 'sample',
  },
  {
    id: 'DataModelEditor',
    name: 'Data model editor',
    description: 'Build and refine a SpotterModel schema with AI-assisted table, join, column, and formula suggestions.',
    author: 'Design Team',
    lastModified: '2026-04-30',
    thumbnail: DataModelEditorThumbnail,
    component: DataModelEditorSample,
    dsComponents: 10,
    customComponents: 13,
    section: 'sample',
  },
];
